### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

### ISSUE THREAD

**Issue by develar** [brianloveswords/buffer-crc32#14]
```
at Buffer (buffer.js:79:13)
    at bufferizeInt (node_modules/buffer-crc32/index.js:62:13)
    at crc32 (node_modules/buffer-crc32/index.js:82:10)
    at Object.<anonymous>.module.exports.Object.<anonymous>.DeflateCRC32Stream.write (node_modules/crc32-stream/lib/deflate-crc32-stream.js:44:21)
```

**Comment by brianloveswords** [comment]
`0.2.6` published

**Comment by caesar** [comment]
This isn't fixed: there's another case a few lines down where `Buffer()` is called without `new`, on line 69. Will send a pull request shortly...

**Comment by caesar** [comment]
Actually `new Buffer()` is deprecated too, though it doesn't trigger a warning yet.
The correct solution would be `Buffer.from()` or `Buffer.allocate()`, depending on the usage...

**Comment by brianloveswords** [comment]
Okay, I'll accept the PR and publish that as a patch update for <6 users, fix the usages to the new node v6 Buffer API, update the engine in package.json and publish that as another version.

**Comment by brianloveswords** [comment]
Done, `0.2.7` using `new Buffer()` for engines <6 and `0.2.8` using `Buffer.alloc` and `Buffer.from` for engines >6 published.

**Comment by caesar** [comment]
Thanks for the quick work @brianloveswords!
But... I just updated, and the change to `Buffer.from()` is causing an error to be thrown – haven't tracked it down (I'm using this via `archiver`, not directly), but it's getting called with a number from somewhere, in which case `Buffer.alloc()` is needed.

Here's a stack trace:
```
buffer.js:108
    throw new TypeError('"value" argument must not be a number');
    ^

TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:108:11)
    at _crc32 (/Users/caesar/code/publican/node_modules/buffer-crc32/index.js:69:18)
    at Function.crc32.unsigned (/Users/caesar/code/publican/node_modules/buffer-crc32/index.js:88:17)
    at module.exports.DeflateCRC32Stream.digest (/Users/caesar/code/publican/node_modules/crc32-stream/lib/deflate-crc32-stream.js:52:16)
    at module.exports.handleStuff (/Users/caesar/code/publican/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:171:23)
    at module.exports.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at module.exports.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by brianloveswords** [comment]
I'll have to dig into it more, I must have a missing test case in my suite. If you can create a reproduceable reduced test case, please submit it!

**Comment by caesar** [comment]
Alright, I'm not familiar with the API (as I said I'm not using this package directly), but I'll check it out this evening if I have time.

Maybe a good idea to unpublish v0.2.8 in the meantime? (I had to downgrade with `npm install buffer-crc32@0.2.7`)

**Comment by caesar** [comment]
Okay, just from a quick look at the code:
- archiver uses a package called crc32-stream.
- `crc32-stream.digest()` calls `crc32.unsigned(0, this.checksum)`
- `crc32.unsigned` calls `_crc32.apply(null, arguments)`
- `_crc32.apply` calls `new Buffer()` – or now, `Buffer.from()` – with its first argument, which in this case is an `int`.

I haven't tried to understand how the code works overall, but I do know that calling `Buffer()` or `new Buffer()` with an `int` is the same as calling `Buffer.alloc()`, *not* `Buffer.from()`.

**Comment by brianloveswords** [comment]
That's just what I figured out too, @caesar. I have a patch incoming.

**Comment by caesar** [comment]
Great, thanks!

**Comment by brianloveswords** [comment]
@caesar mind taking a look at this patchset and see if it looks right based on what you found out? https://github.com/brianloveswords/buffer-crc32/commit/3e4ec8f3a909c90e7d5d5acf97063df988f06f87

**Comment by caesar** [comment]
Works for me. 👍 

Incidentally, unrelated to this issue, but the first line `var Buffer = require('buffer').Buffer;` is unnecessary since `Buffer` is a global in Node.

**Comment by brianloveswords** [comment]
Thanks @caesar! That first line was necessary for `browserify` ages ago, but I'm not sure it still is – since it doesn't harm anything, I'd like to keep it in for backwards compatibility.

**Comment by caesar** [comment]
Sure, I was just thinking of Node, but for Browserify it makes sense.

**Comment by caesar** [comment]
One more thought, your error message states: "input must be a number or a string", but this is untrue – you first check for `Buffer.isBuffer(buf)`, so a Buffer is a valid input too.

**Comment by brianloveswords** [comment]
Good call, I'll fix that up.
