### ISSUE TITLE
Same issue with 0.2.12. Expected version ">=6.0.0"

### ISSUE THREAD

**Issue by jh2oman** [brianloveswords/buffer-crc32#17]
The engine "node" is incompatible with this module. Expected version ">=6.0.0".
node -v
v4.5.0

**Comment by CobaltTiger** [comment]
Incidentally, we've got an issue where node 5.1.1 tries to invoke Buffer.alloc -- which wasn't added until Node 5.10

Kind of curious why something that wasn't (at least, not obviously) broken got "fixed" :)

**Comment by brianloveswords** [comment]
@CobaltTiger for why something that wasn't "broken" got fixed, see https://medium.com/@jasnell/node-js-buffer-api-changes-3c21f1048f9. Because there are no external API changes which would warrent a minor release, and there are potential security concerns, which is what `patch` is made for, if at all possible I want to keep this a patch update since I can't go figure out all the dependents and make them update.

**Comment by brianloveswords** [comment]
@jh2oman `0.2.13` should fix your issue. @CobaltTiger, gotta dig into yours more.

**Comment by brianloveswords** [comment]
@CobaltTiger if you get a second can you give me a stack trace using `0.2.12` or `0.2.13`?

**Comment by jh2oman** [comment]
@brianloveswords thank you very much. Unfortunately out until after Thanksgiving so I won't be able to verify till then.

**Comment by brianloveswords** [comment]
@jh2oman sorry I wasn't able to get to it until you were out, let me know if it fixes your issue once you get back and I'll close this. Thanks!

**Comment by CobaltTiger** [comment]
@brianloveswords Aha, security issues I can completely understand. I had not seen these writeups -- and even at a glance I can see that being an issue that would indeed be best addressed through a patch.

As far as a stack trace goes, I'm unfortunately not able to easily produce one. In my case, the offending first-level dependent is a plugin called grunt-aws-lambda, which leverages archiver ~0.14.4. It proceeds to call npm.load and set its log level to silent. :) I do see that its only interaction with archiver (which, itself, seems to be the culprit as it is the only thing using buffer-crc32) is that it creates an archiver('zip');
We're using different node versions between our personal computers and our build servers (I know...) and the issue does not present itself on Node v4.4.5, but does break in 5.1.1 -- maybe a more strict version-check is in order before using Buffer.alloc vs. new Buffer()? As previously mentioned, alloc was only available in >=5.10

If you really need the stack trace, I can try tomorrow to make that child npm process more talkative.

**Comment by brianloveswords** [comment]
@CobaltTiger yeah, the stack trace would help – `0.2.12` tries to be smart and fall back to `new Buffer` if `alloc` and `from` are not available. I tried testing it locally using 5.1.1, it passes the test suite and I've confirmed it's falling back, so I'm not sure what's going on.

**Comment by fengmk2** [comment]
@brianloveswords I think recently publish versions broken a lot. And I think those verions should be 0.3.x not 0.2.x.

**Comment by CobaltTiger** [comment]
I feel like yeah, if it *does* have to go to a new minor version, 0.2.x
should immediately have a deprecation warning slapped on it. Won't do a
whole lot to force outdated plugins to update, but I'm pretty sure it'll
encourage active projects to get up to date.

**Comment by brianloveswords** [comment]
@fengmk2 please file an issue with a stack trace if you're having one. There's definitely been some churn with this update to the new Buffer APIs while still trying to remain backwards compatible, but I believe it's in the best interest of the community to provide this as a patch update.

**Comment by CobaltTiger** [comment]
@brianloveswords I'm sorry, I'm unable to produce a stack trace on my end. I did notice that npm was pulling down only 0.2.8 in previous builds -- perhaps that's the crux of the issue.

**Comment by jh2oman** [comment]
@brianloveswords 0.2.13 Fixes my issue. Thank you very much!

**Comment by brianloveswords** [comment]
@jh2oman great, thanks for following up and sorry again for breaking it!
