### ISSUE TITLE
Deprecated Buffer API

### ISSUE THREAD

**Issue by kibertoad** [brianloveswords/buffer-crc32#20]
This library uses `new Buffer`, which is deprecated. `Buffer.allocUnsafe` should be used instead

Would you be open to a PR fixing this?

**Comment by brianloveswords** [comment]
I'd be open to that  PR!

**Comment by kibertoad** [comment]
@brianloveswords Thank you! Since Travis CI stopped working long time ago (and is no longer a good option for OSS), I've opened a PR to add GitHub Actions CI, to ensure that changes won't break anything: https://github.com/brianloveswords/buffer-crc32/pull/21

**Comment by kibertoad** [comment]
@brianloveswords I only now realised that you actually have a check in your code already that only uses old API for old Node versions. Do you still intend to support all of Node versions, or you are open to releasing a new semver major dropping support for anything below Node 8?

**Comment by brianloveswords** [comment]
@kibertoad I'm open to a major bump that drops old versions

**Comment by brianloveswords** [comment]
fixed by #27
